#!/bin/sh
print_help() {
	# shellcheck disable=SC2016
	printf -- 'installs infra files into $PREFIX\n'
	printf -- '\t-h prints this message\n'
	printf -- '\t-n pass -nv to stow\n'
}

while getopts hn opt; do
	case "$opt" in
	h)
		print_help
		exit
		;;
	n)
		STOWOPTS="-nv"
		;;
	*)
		print_help
		exit 1
		;;
	esac
done
shift "$((OPTIND - 1))"

stow $STOWOPTS -t "$PREFIX"/usr/local distro-repo/
