---
nginx_sites:
  - builds.managarm.org
  - docs.managarm.org
  - mirrors.managarm.org
  - repos.managarm.org
  - pkgs.managarm.org # removed, a redirect for now
  - ci.managarm.org # removed, a redirect for now
  - hades.hosts.managarm.org
  - relay.managarm.org

nginx_streams:
  - rsync.managarm.org

rsyncd_modules:
  - docs
  - cbuildrt
  - buildenv

acme_domains: "{{ nginx_sites + nginx_streams }}"

bridge:
  irc_network: irc.libera.chat
  irc_port: 6697 # requires tls
  message_base_url: https://relay.managarm.org/idb/
  channels:
    "678608576151027734":
      irc_channel: '#managarm'
    "678613590646849576":
      irc_channel: '#managarm-dev'
    "678613510237978625":
      irc_channel: '#managarm-mlibc'
    "779254963557761044":
      irc_channel: '#managarm-lai'
    "707189087269814302":
      irc_channel: '#managarm-ports'
    "685151198453825566":
      irc_channel: '#managarm-xbstrap'
    "678613670980222987":
      irc_channel: '#managarm-misc'
    "888101472313700372":
      irc_channel: '#managarm-riscv'

# vim: sw=2 et :
