---
nginx_sites:
  - builds.managarm.org
  - docs.managarm.org
  - mirrors.managarm.org
  - repos.managarm.org
  - pkgs.managarm.org # removed, a redirect for now
  - ci.managarm.org # removed, a redirect for now
  - hades.hosts.managarm.org
  - hwci.managarm.org

nginx_streams:
  - rsync.managarm.org

rsyncd_modules:
  - docs
  - cbuildrt
  - buildenv

acme_domains: "{{ nginx_sites + nginx_streams }}"
acme_units:
  - nginx.service
  - dovecot.service
  - postfix.service

# watch out not to add HTML tags here
# the jinja context ansible uses is scuffed
docs_modules:
  - path: handbook
    name: The Managarm handbook
    description: A conceptual and technical overview of the Managarm system
    source: https://github.com/managarm/managarm/tree/master/docs
  - path: hel-api
    name: Hel API reference
    description: Doxygen reference for the Hel system call layer
    source: https://github.com/managarm/managarm/tree/master/hel
  - path: libasync
    name: libasync
    description: libasync conceptual overview and API reference
    source: https://github.com/managarm/libasync/tree/master/docs

hwci_virtualenv: "/usr/local/share/hwci/venv"

# vim: sw=2 et :
