---
- name: xbbs_coordinator_services
  become: yes
  become_user: root
  ansible.builtin.systemd:
    name: xbbs-{{ item }}
    daemon_reload: yes
    enabled: yes
    state: restarted
  loop: ["coordinator", "web", "webhooks"]

- name: fcgiwrap_service
  become: yes
  ansible.builtin.systemd:
    name: fcgiwrap.{{ item }}
    daemon_reload: yes
    enabled: yes
    state: restarted
  loop: [socket, service]

# vim: sw=2 et :
