#!/usr/bin/env bash
_approve_distro_completions_present() {
	local x
	for x in "${COMP_WORDS[@]}"; do
		if [ "$x" == "$1" ]; then
			return 0
		fi
	done
	return 1
}

_approve_distro_completions() {
	local x
	options=""
	src=
	dst=
	eval "$(python3 -c '
import toml
import shlex

with open("/etc/approve-distro.toml", "r") as f:
	repos = toml.load(f).get("repositories", {})
	print("project_dir=" + shlex.quote(repos.get("project_dir", "")))
	print("dst=" + shlex.quote(repos.get("distro_path", "")))
')"
	[ "$project_dir" ] || return
	latest="$(printf '%s\n' "$project_dir"/*T* | sort -r | head -n1)"
	[ "$latest" ] || return
	src="$latest/repo/packages/x86_64/"
	for x in "-h" "$src"/*.xbps; do
		if [[ "$src/*.xbps" = $x ]]; then continue; fi
		x="${x##*/}"
		x="${x%.xbps}"
		if ! _approve_distro_completions_present "$x" \
			&& ! [ -e "${dst}/${x}.xbps" ]
		then
			options="$options $x"
		fi
	done
	# shellcheck disable=SC2207
	COMPREPLY+=($(compgen -W "${options# }" -- "${COMP_WORDS[${COMP_CWORD}]}"))
	return
}

complete -F _approve_distro_completions approve-distro
