---
- name: xbbs_worker
  become: yes
  become_user: root
  ansible.builtin.systemd:
    name: xbbs-worker
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: update_cbuildrt_rootfs
  become: yes
  become_user: xbbs
  ansible.builtin.command: "/var/lib/xbbs/xbstrap_home/update_rootfs.sh"
  args:
    creates: "/var/lib/cbuildrt/managarm-buildenv/dev/null"

# vim: sw=2 et :
