---
# This could have been merged with update_coordinator if ansible.builtin.pip
# behaved sanely (actually checked if an upgrade happens when state=latest is
# passed) instead of just reporting unchanged every time
- hosts: coordinators
  become: yes
  tasks:
    - ansible.builtin.pip: name=git+https://github.com/managarm/xbbs.git state=forcereinstall
    - ansible.builtin.systemd: unit=xbbs-web state=restarted
    - ansible.builtin.systemd: unit=xbbs-webhooks state=restarted
    - ansible.builtin.systemd: unit=xbbs-coordinator state=restarted

# vim: et sw=2 :
