---
- name: Add irc-discord-bridgebot group
  become: yes
  ansible.builtin.group:
    name: message-relays
    system: true
    state: present

- name: Add irc-discord-bridgebot user
  become: yes
  ansible.builtin.user:
    state: present
    name: irc-discord-bridgebot
    group: message-relays
    comment: A message relay between IRC <-> Discord
    system: true
    shell: "/bin/false"

  # TODO(arsen): handle updates better
- name: Download the bridge
  become: yes
  ansible.builtin.get_url:
    url: https://cdn.aarsen.me/builds/irc-discord-bridgebot/master
    dest: /usr/local/bin/irc-discord-bridgebot
    mode: 0755
  notify: restart_bridgebot

- name: Install the service
  become: yes
  ansible.builtin.template:
    src: "irc-discord-bridgebot.service.j2"
    dest: "/etc/systemd/system/irc-discord-bridgebot.service"
    owner: root
    group: root
    mode: 0644
  notify: restart_bridgebot

- name: Generate the irc-discord-bridgebot config
  become: yes
  ansible.builtin.template:
    dest: /etc/idb.toml
    src: idb.toml.j2
    owner: root
    group: message-relays
    mode: 0640

# vim: sw=2 et :
